//Source code generated by AppGPT (www.appgpt.tech)
//to be autogenerated as template, one per resource
import { Entity, Column, PrimaryGeneratedColumn } from 'typeorm';

@Entity('HousingOptions')
export class HousingOptionsEntity {
  @PrimaryGeneratedColumn()
  id: number;

  @Column('bool', { nullable: true })
  safe: boolean;

  @Column('bool', { nullable: true })
  affordable: boolean;

  @Column('text', { nullable: true })
  filters: string;

  @Column('real', { nullable: true })
  rent: number;
}
