//Source code generated by AppGPT (www.appgpt.tech)
//to be autogenerated as template, one per resource
import { Entity, Column, PrimaryGeneratedColumn } from 'typeorm';

@Entity('SupportServices')
export class SupportServicesEntity {
  @PrimaryGeneratedColumn()
  id: number;

  @Column('text', { nullable: true })
  NGOs: string;

  @Column('text', { nullable: true })
  police: string;

  @Column('bool', { nullable: true })
  safety: boolean;

  @Column('bool', { nullable: true })
  antibully: boolean;
}
