//Source code generated by AppGPT (www.appgpt.tech)
import { Card, CardContent, CardHeader } from '@mui/material';
export const Dashboard = () => (
  <Card>
    <CardHeader title="ShelterWay" />
    <CardContent>
      "ShelterWay" is a groundbreaking app designed to support the unique needs
      of children with parents in the sex work industry in India. With a range
      of features including AI-powered identity protection, anti-bullying tools,
      safe housing locators, and personalized educational support, ShelterWay
      offers a comprehensive platform aimed at addressing the challenges these
      children face. By prioritizing user-friendly interfaces, privacy, and
      culturally sensitive design, ShelterWay aims to provide a safe and
      empowering space for children and caregivers alike, fostering resilience
      and opportunities for a brighter future.
      <p>
        Built with{' '}
        <a
          href="https://www.appgpt.tech"
          target="_blank"
          rel="noopener noreferrer"
        >
          AppGPT
        </a>
      </p>
    </CardContent>
  </Card>
);
