//Source code generated by AppGPT (www.appgpt.tech)
let data: any = {
  defaultData: {
    Users: [
      { name: 'name 1', age: 1, contact: 'contact 1', id: 37 },
      { name: 'name 2', age: 2, contact: 'contact 2', id: 48 },
      { name: 'name 3', age: 3, contact: 'contact 3', id: 96 },
      { name: 'name 4', age: 4, contact: 'contact 4', id: 96 },
      { name: 'name 5', age: 5, contact: 'contact 5', id: 8 },
    ],
    SupportServices: [
      {
        NGOs: 'NGOs 1',
        police: 'police 1',
        safety: false,
        antibully: true,
        id: 48,
      },
      {
        NGOs: 'NGOs 2',
        police: 'police 2',
        safety: true,
        antibully: true,
        id: 18,
      },
      {
        NGOs: 'NGOs 3',
        police: 'police 3',
        safety: false,
        antibully: false,
        id: 71,
      },
      {
        NGOs: 'NGOs 4',
        police: 'police 4',
        safety: true,
        antibully: true,
        id: 96,
      },
      {
        NGOs: 'NGOs 5',
        police: 'police 5',
        safety: false,
        antibully: true,
        id: 52,
      },
    ],
    HousingOptions: [
      {
        safe: false,
        affordable: false,
        filters: 'filters 1',
        rent: 0.28,
        id: 78,
      },
      {
        safe: false,
        affordable: false,
        filters: 'filters 2',
        rent: 0.05,
        id: 39,
      },
      {
        safe: true,
        affordable: true,
        filters: 'filters 3',
        rent: 0.91,
        id: 53,
      },
      { safe: true, affordable: true, filters: 'filters 4', rent: 0.2, id: 34 },
      {
        safe: false,
        affordable: false,
        filters: 'filters 5',
        rent: 0.98,
        id: 64,
      },
    ],
    Reports: [
      { fileAComplaint: 'fileAComplaint 1', report: 'report 1', id: 6 },
      { fileAComplaint: 'fileAComplaint 2', report: 'report 2', id: 94 },
      { fileAComplaint: 'fileAComplaint 3', report: 'report 3', id: 91 },
      { fileAComplaint: 'fileAComplaint 4', report: 'report 4', id: 28 },
      { fileAComplaint: 'fileAComplaint 5', report: 'report 5', id: 98 },
    ],
  },
};
export default data;
