//Source code generated by AppGPT (www.appgpt.tech)
import { mergeTranslations } from 'ra-core';
import polyglotI18nProvider from 'ra-i18n-polyglot';
import enOriginal from 'ra-language-english';
import frOriginal from 'ra-language-french';

const enResources = {
  resources: {
    Users: {
      name: 'Users',
      fields: { name: 'Name', age: 'Age', contact: 'Contact', id: 'id' },
    },
    SupportServices: {
      name: 'Support Services',
      fields: {
        NGOs: 'Ngos',
        police: 'Police',
        safety: 'Safety',
        antibully: 'Antibully',
        id: 'id',
      },
    },
    HousingOptions: {
      name: 'Housing Options',
      fields: {
        safe: 'Safe',
        affordable: 'Affordable',
        filters: 'Filters',
        rent: 'Rent',
        id: 'id',
      },
    },
    Reports: {
      name: 'Reports',
      fields: { fileAComplaint: 'File Acomplaint', report: 'Report', id: 'id' },
    },
  },
};
const frResources = {
  resources: {
    Users: {
      name: 'Users (fr)',
      fields: {
        name: 'Name (fr)',
        age: 'Age (fr)',
        contact: 'Contact (fr)',
        id: 'id',
      },
    },
    SupportServices: {
      name: 'Support Services (fr)',
      fields: {
        NGOs: 'Ngos (fr)',
        police: 'Police (fr)',
        safety: 'Safety (fr)',
        antibully: 'Antibully (fr)',
        id: 'id',
      },
    },
    HousingOptions: {
      name: 'Housing Options (fr)',
      fields: {
        safe: 'Safe (fr)',
        affordable: 'Affordable (fr)',
        filters: 'Filters (fr)',
        rent: 'Rent (fr)',
        id: 'id',
      },
    },
    Reports: {
      name: 'Reports (fr)',
      fields: {
        fileAComplaint: 'File Acomplaint (fr)',
        report: 'Report (fr)',
        id: 'id',
      },
    },
  },
};

const en = mergeTranslations(enOriginal, enResources);
const fr = mergeTranslations(frOriginal, frResources);

const translations = { en, fr };
export const i18nProvider = polyglotI18nProvider(
  (locale) => translations[locale],
  'en', //default locale
  [
    { locale: 'en', name: 'English' },
    { locale: 'fr', name: 'Français' },
  ],
);
